// Traditional Chinese UTF-8; Twapweb Site translated; twapweb_AT_gmail_DOT_com
// 繁體中文 UTF-8 ；數位應用坊製作； twapweb_AT_gmail_DOT_com


tinyMCE.addToLang('',{
theme_style_select : '-- 式樣 --',
theme_code_desc : '編輯 HTML 碼',
theme_code_title : 'HTML 碼編輯器',
theme_code_wordwrap : '字詞環繞',
theme_sub_desc : '下標',
theme_sup_desc : '上標',
theme_hr_desc : '插入水平線',
theme_custom1_desc : '自訂說明在此輸入',
insert_image_border : '框線',
insert_image_dimensions : '尺寸',
insert_image_vspace : '圖像上下側間距',
insert_image_hspace : '圖像左右邊間距',
insert_image_align : '垂直對齊',
insert_image_align_default : '-- 未設置 --',
insert_image_align_baseline : '底線',
insert_image_align_top : '頂端',
insert_image_align_middle : '中線',
insert_image_align_bottom : '底部',
insert_image_align_texttop : '文字頂端',
insert_image_align_absmiddle : '絕對中線',
insert_image_align_absbottom : '絕對底部',
insert_image_align_left : '左',
insert_image_align_right : '右',
theme_font_size : '-- 字體大小 --',
theme_fontdefault : '-- 字體選擇 --',
theme_block : '-- 格式 --',
theme_paragraph : '段落',
theme_div : '分界',
theme_address : '位置',
theme_pre : '內定格式',
theme_h1 : '標題一',
theme_h2 : '標題二',
theme_h3 : '標題三',
theme_h4 : '標題四',
theme_h5 : '標題五',
theme_h6 : '標題六',
theme_colorpicker_title : '選取顏色',
theme_colorpicker_apply : '套用',
theme_forecolor_desc : '選取文字顏色',
theme_backcolor_desc : '選取背景顏色',
theme_charmap_title : '選取自訂字元',
theme_charmap_desc : '插入自訂字元',
theme_visualaid_desc : '切換指示或非可見元件',
insert_anchor_title : '插入或編輯連結點',
insert_anchor_name : '連結點名稱',
theme_anchor_desc : '插入或編輯連結點',
theme_insert_link_titlefield : '標題',
theme_clipboard_msg : '在 Mozilla 和 Firefox 中無法使用複製或剪下或貼上功能。\n需要更多關於此的訊息嗎？',
theme_path : '路徑',
link_list : '連結列表',
image_list : '圖檔列表',
browse : '瀏覽',
image_props_desc : '圖檔屬性',
class_name : '分類',
about_title : '關於 TinyMCE',
about : '關於',
license : '授權',
plugins : '應用套件',
plugin : '應用套件',
author : '作者',
version : '版本',
loaded_plugins : '已載入應用套件',
help : '協助',
not_set : '-- 未設置 --',
close : '關閉',
toolbar_focus : '快速啟用工具紐 - Alt+Q；快速啟用編輯器 - Alt-Z；快速移至元件路徑 - Alt-X'
});
