// Traditional Chinese UTF-8; Twapweb Site translated; twapweb_AT_gmail_DOT_com
// 繁體中文 UTF-8 ；數位應用坊製作； twapweb_AT_gmail_DOT_com

tinyMCE.addToLang('advlink',{
general_tab : '一般',
popup_tab : '跳現視窗',
events_tab : '事件',
advanced_tab : '進階',
general_props : '一般屬性',
popup_props : '跳現視窗屬性',
event_props : '事件屬性',
advanced_props : '進階屬性',
popup_opts : '選項',
anchor_names : '連結點',
target_same : '於此視窗或框架中開啟',
target_parent : '於上層視窗或框架中開啟',
target_top : '於主框架中開啟（會取代全部框架）',
target_blank : '於新視窗中開啟',
popup : 'Javascript 跳現視窗',
popup_url : '跳現視窗網址',
popup_name : '視窗名稱',
popup_return : '插入 "禁回上頁"',
popup_scrollbars : '顯示移動軸',
popup_statusbar : '顯示狀態列',
popup_toolbar : '顯示工具列',
popup_menubar : '顯示選單列',
popup_location : '顯示位置列',
popup_resizable : '可大小化視窗',
popup_dependent : '從屬性（僅適用 Mozilla / Firefox ）',
popup_size : '大小',
popup_position : '位置（ X / Y 軸）',
id : '編碼',
style: '式樣',
classes : '分類',
target_name : '對象名稱',
target_langcode : '對象語言',
langcode : '語碼',
encoding : '對象字元編碼',
mime : '對象 MIME 型式',
rel : '將網頁與對象產生關聯',
rev : '將對象與網頁產生關聯',
tabindex : '標籤索引',
accesskey : '存取鍵',
ltr : '由左至右',
rtl : '由右至左'
});
